NBA_TEAM_SHORT_NAME = {
    'ATL': 'Hawks', 
    'BOS': 'Celtics', 
    'BKN': 'Nets', 
    'CHA': 'Hornets', 
    'CHI': 'Bulls', 
    'CLE': 'Cavaliers', 
    'DAL': 'Mavericks', 
    'DEN': 'Nuggets', 
    'DET': 'Pistons', 
    'GSW': 'Warriors', 
    'HOU': 'Rockets', 
    'IND': 'Pacers', 
    'LAC': 'Clippers', 
    'LAL': 'Lakers', 
    'MEM': 'Grizzlies', 
    'MIA': 'Heat', 
    'MIL': 'Bucks', 
    'MIN': 'Timberwolves', 
    'NOP': 'Pelicans', 
    'NYK': 'Knicks', 
    'OKC': 'Thunder', 
    'ORL': 'Magic', 
    'PHI': '76ers', 
    'PHX': 'Suns', 
    'POR': 'Trail Blazers', 
    'SAC': 'Kings', 
    'SAS': 'Spurs', 
    'TOR': 'Raptors',
    'USA': 'USA', 
    'UTA': 'Jazz', 
    'WAS': 'Wizards',
    'WLD': 'World',
    'WST': 'West',
    'EST': 'East',
    'RMD': 'Real Madrid',
    'MAC': 'Maccabi Haifa',
    'SLA': 'San Lorenzo',
    'LBN': 'LeBron',
    'STP': 'Stephen',
    'AWY': 'Away',
    'HME': 'Home',
    'GNS': 'Giannis',
    'WLB': 'Wilbon',
    'DRT': 'Durant',
    'WOR': 'Worthy',
    'IAH': 'Isiah',
    'PAY': 'Payton',
    'BAR': 'Barry'
}