NBA_TEAM_SHORT_NAME = {
    'ATL': 'Hawks', 
    'BOS': 'Celtics', 
    'BKN': 'Nets', 
    'CHA': 'Hornets', 
    'CHI': 'Bulls', 
    'CLE': 'Cavaliers', 
    'DAL': 'Mavericks', 
    'DEN': 'Nuggets', 
    'DET': 'Pistons', 
    'GSW': 'Warriors', 
    'HOU': 'Rockets', 
    'IND': 'Pacers', 
    'LAC': 'Clippers', 
    'LAL': 'Lakers', 
    'MEM': 'Grizzlies', 
    'MIA': 'Heat', 
    'MIL': 'Bucks', 
    'MIN': 'Timberwolves', 
    'NOP': 'Pelicans', 
    'NYK': 'Knicks', 
    'OKC': 'Thunder', 
    'ORL': 'Magic', 
    'PHI': '76ers', 
    'PHX': 'Suns', 
    'POR': 'Trail Blazers', 
    'SAC': 'Kings', 
    'SAS': 'Spurs', 
    'TOR': 'Raptors',
    'USA': 'USA', 
    'UTA': 'Jazz', 
    'WAS': 'Wizards',
    'WLD': 'World',
    'WST': 'West',
    'EST': 'East',
    'RMD': 'Real Madrid',
    'MAC': 'Maccabi Haifa',
    'SLA': 'San Lorenzo',
    'LBN': 'LeBron',
    'STP': 'Stephen',
    'AWY': 'Away',
    'HME': 'Home',
    'GNS': 'Giannis',
    'WLB': 'Wilbon',
    'DRT': 'Durant',
    'WOR': 'Worthy',
    'IAH': 'Isiah',
    'PAY': 'Payton',
    'BAR': 'Barry'
}

# basketball-reference.com
NBA_FULL_NAME = {
    'ATL': 'Atlanta Hawks', 
    'BOS': 'Boston Celtics',
    'BRK': 'Brooklyn Nets',
    'CHO': 'Charlotte Hornets',
    'CHI': 'Chicago Bulls',
    'CLE': 'Cleveland Cavaliers',
    'DAL': 'Dallas Mavericks',
    'DEN': 'Denver Nuggets',
    'DET': 'Detroit Pistons',
    'GSW': 'Golden State Warriors',
    'HOU': 'Houston Rockets',
    'IND': 'Indiana Pacers',
    'LAC': 'Los Angeles Clippers',
    'LAL': 'Los Angeles Lakers',
    'MEM': 'Memphis Grizzlies',
    'MIA': 'Miami Heat',
    'MIL': 'Milwaukee Bucks',
    'MIN': 'Minnesota Timberwolves',
    'NOP': 'New Orleans Pelicans',
    'NYK': 'New York Knicks',
    'OKC': 'Oklahoma City Thunder',
    'ORL': 'Orlando Magic',
    'PHI': 'Philadelphia 76ers',
    'PHO': 'Phoenix Suns',
    'POR': 'Portland Trail Blazers',
    'SAC': 'Sacramento Kings',
    'SAS': 'San Antonio Spurs',
    'TOR': 'Toronto Raptors',
    'UTA': 'Utah Jazz',
    'WAS': 'Washington Wizards'    
}

{
    'IND': 'INDIANA PACERS',
    'BOS': 'BOSTON CELTICS',
    'POR': 'PORTLAND TRAIL BLAZERS',
    'OKC': 'OKLAHOMA CITY THUNDER',
    'GSW': 'GOLDEN STATE WARRIORS',
    'MEM': 'MEMPHIS GRIZZLIES',
    'CHI': 'CHICAGO BULLS',
    'LAC': 'LA CLIPPERS',
    'HOU': 'HOUSTON ROCKETS',
    'WAS': 'WASHINGTON WIZARDS',
    'UTA': 'UTAH JAZZ',
    'SAS': 'SAN ANTONIO SPURS',
    'CLE': 'CLEVELAND CAVALIERS',
    'TOR': 'TORONTO RAPTORS',
    'ATL': 'ATLANTA HAWKS',
    'MIL': 'MILWAUKEE BUCKS',
    'LAL': 'LOS ANGELES LAKERS',
    'CHA': 'CHARLOTTE HORNETS',
    'DEN': 'DENVER NUGGETS',
    'PHX': 'PHOENIX SUNS',
    'NYK': 'NEW YORK KNICKS',
    'BKN': 'BROOKLYN NETS',
    'MIA': 'MIAMI HEAT',
    'PHI': 'PHILADELPHIA 76ERS',
    'DAL': 'DALLAS MAVERICKS',
    'MIN': 'MINNESOTA TIMBERWOLVES',
    'NOP': 'NEW ORLEANS PELICANS',
    'SAC': 'SACRAMENTO KINGS',
    'ORL': 'ORLANDO MAGIC',
    'DET': 'DETROIT PISTONS'
}